Microsoft Windows [Version 10.0.19045.3930]
(c) Microsoft Corporation. All rights reserved.

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project>django-admin startproject MIS_projectDjango_it

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project>cd MIS_projectDjango_it

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>django-admin startapp STUDENT

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>django-admin startapp ACCOUNT

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>django-admin startapp LIBRARY

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\apps\config.py", line 193, in create
    import_module(entry)
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1318, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app_name'
C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it\MIS_projectDjango_it\settings.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 516, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1318, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'project_name'
C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it\MIS_projectDjango_it\settings.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
ACCOUNT.finance: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the AccountConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

System check identified 1 issue (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\servers\basehttp.py", line 48, in get_internal_wsgi_application
    return import_string(app_path)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1318, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'project_name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\commands\runserver.py", line 139, in inner_run
    handler = self.get_handler(*args, **options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\staticfiles\management\commands\runserver.py", line 31, in get_handler
    handler = super().get_handler(*args, **options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\commands\runserver.py", line 78, in get_handler
    return get_internal_wsgi_application()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\servers\basehttp.py", line 50, in get_internal_wsgi_application
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: WSGI application 'project_name.wsgi.application' could not be loaded; Error importing module.

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
ACCOUNT.finance: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the AccountConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

System check identified 1 issue (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
February 05, 2024 - 22:46:34
Django version 5.0.1, using settings 'MIS_projectDjango_it.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

[05/Feb/2024 22:46:47] "GET / HTTP/1.1" 200 10629
[05/Feb/2024 22:46:48] "GET / HTTP/1.1" 200 10629
Not Found: /favicon.ico
[05/Feb/2024 22:46:50] "GET /favicon.ico HTTP/1.1" 404 2124
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\sessions\backends\base.py", line 187, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\sites.py", line 228, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\sites.py", line 201, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\middleware.py", line 33, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\middleware.py", line 13, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\__init__.py", line 209, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\__init__.py", line 62, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\sessions\backends\base.py", line 53, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\sessions\backends\base.py", line 192, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\sessions\backends\db.py", line 42, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 643, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1926, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
[05/Feb/2024 22:46:59] "GET /admin/ HTTP/1.1" 500 204380
Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\sessions\backends\base.py", line 187, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\sites.py", line 259, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\sites.py", line 228, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\sites.py", line 201, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\middleware.py", line 33, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\middleware.py", line 13, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\__init__.py", line 209, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\__init__.py", line 62, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\sessions\backends\base.py", line 53, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\sessions\backends\base.py", line 192, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\sessions\backends\db.py", line 42, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 643, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1926, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DEVAKI DESHPANDE\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
[05/Feb/2024 22:47:01] "GET /admin/ HTTP/1.1" 500 204104

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>python manage.py makemigrations
System check identified some issues:

WARNINGS:
ACCOUNT.finance: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the AccountConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
Migrations for 'ACCOUNT':
  ACCOUNT\migrations\0001_initial.py
    - Create model finance
Migrations for 'LIBRARY':
  LIBRARY\migrations\0001_initial.py
    - Create model books
Migrations for 'STUDENT':
  STUDENT\migrations\0001_initial.py
    - Create model Country
    - Create model Marks
    - Create model Subject1
    - Create model City

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>python manage.py migrate
System check identified some issues:

WARNINGS:
ACCOUNT.finance: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the AccountConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
Operations to perform:
  Apply all migrations: ACCOUNT, LIBRARY, STUDENT, admin, auth, contenttypes, sessions
Running migrations:
  Applying ACCOUNT.0001_initial... OK
  Applying LIBRARY.0001_initial... OK
  Applying STUDENT.0001_initial... OK
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
ACCOUNT.finance: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the AccountConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

System check identified 1 issue (0 silenced).
February 05, 2024 - 22:48:05
Django version 5.0.1, using settings 'MIS_projectDjango_it.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

[05/Feb/2024 22:48:12] "GET /admin/ HTTP/1.1" 302 0
[05/Feb/2024 22:48:12] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
[05/Feb/2024 22:48:12] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[05/Feb/2024 22:48:12] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[05/Feb/2024 22:48:12] "GET /static/admin/css/login.css HTTP/1.1" 304 0
[05/Feb/2024 22:48:12] "GET /static/admin/js/theme.js HTTP/1.1" 304 0
[05/Feb/2024 22:48:12] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[05/Feb/2024 22:48:12] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[05/Feb/2024 22:48:12] "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
[05/Feb/2024 22:48:16] "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4320

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>python manage.py createsuperuser
System check identified some issues:

WARNINGS:
ACCOUNT.finance: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the AccountConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
Username (leave blank to use 'devakideshpande'): admin
Email address: devkideshpande06@gmail.com
Password:
Password (again):
Error: Your passwords didn't match.
Password:
Password (again):
This password is too short. It must contain at least 8 characters.
This password is entirely numeric.
Bypass password validation and create user anyway? [y/N]: N
Password:
Operation cancelled.

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>python manage.py createsuperuser
System check identified some issues:

WARNINGS:
ACCOUNT.finance: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the AccountConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
Username (leave blank to use 'devakideshpande'): MisAdmin
Email address: devkideshpande06@gamil.com
Password:
Password (again):
Superuser created successfully.

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>python manage.py makemigrations
System check identified some issues:

WARNINGS:
ACCOUNT.finance: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the AccountConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
No changes detected

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>python manage.py migrate
System check identified some issues:

WARNINGS:
ACCOUNT.finance: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the AccountConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
Operations to perform:
  Apply all migrations: ACCOUNT, LIBRARY, STUDENT, admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
ACCOUNT.finance: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the AccountConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

System check identified 1 issue (0 silenced).
February 05, 2024 - 22:52:47
Django version 5.0.1, using settings 'MIS_projectDjango_it.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

[05/Feb/2024 22:52:49] "GET /admin/ HTTP/1.1" 302 0
[05/Feb/2024 22:52:49] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
[05/Feb/2024 22:52:54] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[05/Feb/2024 22:52:54] "GET /admin/ HTTP/1.1" 200 8770
[05/Feb/2024 22:52:54] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[05/Feb/2024 22:52:54] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[05/Feb/2024 22:52:54] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[05/Feb/2024 22:53:09] "GET /admin/STUDENT/city/add/ HTTP/1.1" 200 12391
[05/Feb/2024 22:53:10] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[05/Feb/2024 22:53:10] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[05/Feb/2024 22:53:10] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[05/Feb/2024 22:53:10] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[05/Feb/2024 22:53:10] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[05/Feb/2024 22:53:10] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[05/Feb/2024 22:53:10] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[05/Feb/2024 22:53:10] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[05/Feb/2024 22:53:10] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[05/Feb/2024 22:53:10] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:53:10] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[05/Feb/2024 22:53:10] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
[05/Feb/2024 22:53:10] "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
[05/Feb/2024 22:53:10] "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
[05/Feb/2024 22:53:19] "GET /admin/STUDENT/country/add/?_to_field=id&_popup=1 HTTP/1.1" 200 4368
[05/Feb/2024 22:53:19] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:53:25] "POST /admin/STUDENT/country/add/?_to_field=id&_popup=1 HTTP/1.1" 200 325
[05/Feb/2024 22:53:25] "GET /static/admin/js/popup_response.js HTTP/1.1" 304 0
[05/Feb/2024 22:53:38] "POST /admin/STUDENT/city/add/ HTTP/1.1" 302 0
[05/Feb/2024 22:53:38] "GET /admin/STUDENT/city/ HTTP/1.1" 200 11335
[05/Feb/2024 22:53:38] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[05/Feb/2024 22:53:38] "GET /static/admin/img/search.svg HTTP/1.1" 304 0
[05/Feb/2024 22:53:38] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:53:38] "GET /static/admin/js/filters.js HTTP/1.1" 304 0
[05/Feb/2024 22:53:38] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
[05/Feb/2024 22:53:38] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
[05/Feb/2024 22:53:44] "GET /admin/STUDENT/marks/add/ HTTP/1.1" 200 10747
[05/Feb/2024 22:53:45] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:53:55] "POST /admin/STUDENT/marks/add/ HTTP/1.1" 302 0
[05/Feb/2024 22:53:55] "GET /admin/STUDENT/marks/ HTTP/1.1" 200 11010
[05/Feb/2024 22:53:55] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:54:01] "GET /admin/STUDENT/marks/add/ HTTP/1.1" 200 10747
[05/Feb/2024 22:54:01] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:54:18] "POST /admin/STUDENT/marks/add/ HTTP/1.1" 302 0
[05/Feb/2024 22:54:18] "GET /admin/STUDENT/marks/ HTTP/1.1" 200 11311
[05/Feb/2024 22:54:18] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:54:23] "GET /admin/STUDENT/country/add/ HTTP/1.1" 200 10128
[05/Feb/2024 22:54:23] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:54:30] "POST /admin/STUDENT/country/add/ HTTP/1.1" 302 0
[05/Feb/2024 22:54:30] "GET /admin/STUDENT/country/ HTTP/1.1" 200 11409
[05/Feb/2024 22:54:30] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:54:34] "GET /admin/STUDENT/city/add/ HTTP/1.1" 200 12460
[05/Feb/2024 22:54:34] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:55:02] "POST /admin/STUDENT/city/add/ HTTP/1.1" 302 0
[05/Feb/2024 22:55:02] "GET /admin/STUDENT/city/ HTTP/1.1" 200 11645
[05/Feb/2024 22:55:02] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:55:08] "GET /admin/LIBRARY/books/add/ HTTP/1.1" 200 10769
[05/Feb/2024 22:55:08] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:55:34] "POST /admin/LIBRARY/books/add/ HTTP/1.1" 302 0
[05/Feb/2024 22:55:34] "GET /admin/LIBRARY/books/ HTTP/1.1" 200 11047
[05/Feb/2024 22:55:34] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:55:40] "GET /admin/STUDENT/subject1/add/ HTTP/1.1" 200 12654
[05/Feb/2024 22:55:40] "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
[05/Feb/2024 22:55:40] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
[05/Feb/2024 22:55:40] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:55:40] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
[05/Feb/2024 22:56:07] "GET /static/admin/img/calendar-icons.svg HTTP/1.1" 200 1094
[05/Feb/2024 22:56:13] "POST /admin/STUDENT/subject1/add/ HTTP/1.1" 302 0
[05/Feb/2024 22:56:13] "GET /admin/STUDENT/subject1/ HTTP/1.1" 200 11783
[05/Feb/2024 22:56:13] "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
[05/Feb/2024 22:56:13] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:56:17] "GET /admin/STUDENT/subject1/add/ HTTP/1.1" 200 12654
[05/Feb/2024 22:56:18] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:56:41] "POST /admin/STUDENT/subject1/add/ HTTP/1.1" 302 0
[05/Feb/2024 22:56:41] "GET /admin/STUDENT/subject1/ HTTP/1.1" 200 12219
[05/Feb/2024 22:56:41] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:56:46] "GET /admin/ACCOUNT/finance/add/ HTTP/1.1" 200 10775
[05/Feb/2024 22:56:46] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:57:16] "POST /admin/ACCOUNT/finance/add/ HTTP/1.1" 302 0
[05/Feb/2024 22:57:17] "GET /admin/ACCOUNT/finance/ HTTP/1.1" 200 11049
[05/Feb/2024 22:57:17] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:57:24] "GET /admin/ HTTP/1.1" 200 12334
[05/Feb/2024 22:57:31] "GET /admin/ACCOUNT/finance/1/change/ HTTP/1.1" 200 11048
[05/Feb/2024 22:57:31] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:57:34] "GET /admin/ HTTP/1.1" 200 12334
[05/Feb/2024 22:57:38] "GET / HTTP/1.1" 200 10629
[05/Feb/2024 22:57:41] "GET /admin/ HTTP/1.1" 200 12334
[05/Feb/2024 22:57:53] "GET /admin/STUDENT/subject1/add/ HTTP/1.1" 200 12654
[05/Feb/2024 22:57:53] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:57:59] "GET /admin/LIBRARY/books/add/ HTTP/1.1" 200 10769
[05/Feb/2024 22:57:59] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:58:32] "POST /admin/LIBRARY/books/add/ HTTP/1.1" 302 0
[05/Feb/2024 22:58:32] "GET /admin/LIBRARY/books/ HTTP/1.1" 200 11390
[05/Feb/2024 22:58:32] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 22:58:51] "GET /admin/ HTTP/1.1" 200 12341
[05/Feb/2024 23:01:55] "GET /admin/ACCOUNT/ HTTP/1.1" 200 5055
[05/Feb/2024 23:01:59] "GET /admin/ACCOUNT/finance/ HTTP/1.1" 200 10836
[05/Feb/2024 23:02:00] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:02:32] "GET /admin/ACCOUNT/finance/add/ HTTP/1.1" 200 10775
[05/Feb/2024 23:02:32] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:03:04] "POST /admin/ACCOUNT/finance/add/ HTTP/1.1" 302 0
[05/Feb/2024 23:03:04] "GET /admin/ACCOUNT/finance/ HTTP/1.1" 200 11368
[05/Feb/2024 23:03:04] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:03:06] "GET /admin/ACCOUNT/finance/add/ HTTP/1.1" 200 10775
[05/Feb/2024 23:03:06] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:03:33] "POST /admin/ACCOUNT/finance/add/ HTTP/1.1" 302 0
[05/Feb/2024 23:03:33] "GET /admin/ACCOUNT/finance/ HTTP/1.1" 200 11694
[05/Feb/2024 23:03:33] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:03:36] "GET /admin/ACCOUNT/finance/add/ HTTP/1.1" 200 10775
[05/Feb/2024 23:03:36] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:04:15] "POST /admin/ACCOUNT/finance/add/ HTTP/1.1" 302 0
[05/Feb/2024 23:04:15] "GET /admin/ACCOUNT/finance/ HTTP/1.1" 200 12018
[05/Feb/2024 23:04:15] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:05:03] "GET /admin/ACCOUNT/ HTTP/1.1" 200 5055
[05/Feb/2024 23:05:05] "GET /admin/ACCOUNT/finance/ HTTP/1.1" 200 11805
[05/Feb/2024 23:05:05] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:07:07] "GET /admin/ HTTP/1.1" 200 12362
[05/Feb/2024 23:07:10] "GET /admin/auth/user/ HTTP/1.1" 200 13214
[05/Feb/2024 23:07:10] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:07:10] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[05/Feb/2024 23:07:20] "GET /admin/auth/user/?q= HTTP/1.1" 200 13374
[05/Feb/2024 23:07:20] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:10:10] "GET /admin/ HTTP/1.1" 200 12362
[05/Feb/2024 23:10:13] "GET /admin/LIBRARY/books/ HTTP/1.1" 200 11183
[05/Feb/2024 23:10:13] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:10:19] "GET /admin/STUDENT/ HTTP/1.1" 200 6319
[05/Feb/2024 23:10:21] "GET /admin/STUDENT/ HTTP/1.1" 200 6319
[05/Feb/2024 23:10:25] "GET /admin/STUDENT/city/ HTTP/1.1" 200 11441
[05/Feb/2024 23:10:25] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:10:47] "GET /admin/STUDENT/city/?q=Nanded HTTP/1.1" 200 11304
[05/Feb/2024 23:10:47] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:11:47] "GET /admin/STUDENT/city/?q=Nanded HTTP/1.1" 200 11304
[05/Feb/2024 23:11:47] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:13:01] "GET /admin/ HTTP/1.1" 200 12362
[05/Feb/2024 23:13:05] "GET /admin/auth/user/add/ HTTP/1.1" 200 12585
[05/Feb/2024 23:13:05] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:14:43] "GET /admin/ACCOUNT/ HTTP/1.1" 200 5055
[05/Feb/2024 23:14:48] "GET /admin/ HTTP/1.1" 200 12362
[05/Feb/2024 23:14:51] "GET /admin/auth/user/add/ HTTP/1.1" 200 12585
[05/Feb/2024 23:14:51] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:15:13] "POST /admin/auth/user/add/ HTTP/1.1" 302 0
[05/Feb/2024 23:15:13] "GET /admin/auth/user/2/change/ HTTP/1.1" 200 24693
[05/Feb/2024 23:15:13] "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
[05/Feb/2024 23:15:13] "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15492
[05/Feb/2024 23:15:13] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:15:13] "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
[05/Feb/2024 23:15:13] "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
[05/Feb/2024 23:15:14] "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
[05/Feb/2024 23:15:14] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[05/Feb/2024 23:18:15] "POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
[05/Feb/2024 23:18:15] "GET /admin/auth/user/ HTTP/1.1" 200 13883
[05/Feb/2024 23:18:15] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:18:55] "GET /admin/auth/user/? HTTP/1.1" 200 13688
[05/Feb/2024 23:18:55] "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[05/Feb/2024 23:20:18] "GET /admin/ HTTP/1.1" 200 12352

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>pip freeze > requirements.txt

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>pip install requirements.txt
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
HINT: You are attempting to install a package literally named "requirements.txt" (which cannot exist). Consider using the '-r' flag to install the packages listed in requirements.txt
ERROR: No matching distribution found for requirements.txt

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>python.exe -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\devaki deshpande\appdata\local\programs\python\python312\lib\site-packages (23.2.1)
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/8a/6a/19e9fe04fca059ccf770861c7d5721ab4c2aebc539889e97c7977528a53b/pip-24.0-py3-none-any.whl.metadata
  Downloading pip-24.0-py3-none-any.whl.metadata (3.6 kB)
Downloading pip-24.0-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 2.1/2.1 MB 5.0 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Uninstalling pip-23.2.1:
      Successfully uninstalled pip-23.2.1
Successfully installed pip-24.0

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>pip install requirements.txt
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
HINT: You are attempting to install a package literally named "requirements.txt" (which cannot exist). Consider using the '-r' flag to install the packages listed in requirements.txt
ERROR: No matching distribution found for requirements.txt

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>history
'history' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>history
'history' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\DEVAKI DESHPANDE\OneDrive\Documents\Devki Deshpande Engineering\ty_sem2\Django Project\MIS_projectDjango_it>